package ru.project.naumenpetshelter.constants;

public enum UserState {
    AWAITING_CHOICE,
    ANIMAL_SELECTION,
    STOP,
    VIEW_ANIMALS,
    ANIMAL_VIEW_SELECTION,
    VIEWING_ALL_ANIMALS,
    VIEWING_ANIMALS_BY_ID,
    VIEWING_ANIMALS_BY_TYPE,
    AWAITING_ANIMAL_TYPE_CHOICE,
    AWAITING_ANIMAL_ID
}
